apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: alonesilva/backend-scm:alpha
        ports:
        - containerPort: 3030
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          value: "bed5a76b9f72829f62bda2db6b23efa0537d60e8"
        - name: NODE_ENV
          value: "staging"
        - name: SECRET_OR_KEY
          value: ""